[workspace]
members = [
    "stack-heap",
    "base-concept",
    "html2md",
    "httpie",
    "thumber",
    "queryer",
    "ownership",
    "tt",
    "closure",
    "kv",
    "rgrep",
    "unsf",
    "concurrency",
    "grpc",
    "proto",
    "grpc2",
    "oop",
    "prost_demo",
    "lock",
]
